version: '3.8'

services:
  app:
    image: 'weatherapp:latest'
    build:
      context: .
    container_name: 'app'
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Moscow

  postgres_db:
    image: 'postgres:15.4-alpine'
    container_name: 'postgres_db'
    environment:
      - POSTGRES_DB=weatherappdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
    driver: local